### ISSUE TITLE
The add command can take the same prefix twice.

### ISSUE THREAD

**Issue by chung-ming** [cs2103-ay1819s2-w11-3/main#127]
Describe the bug
If the user types the same prefix twice for the add command, it automatically takes the second prefix by default but this hasn't been mentioned anywhere in user guide

To Reproduce

    Type the command - add n/National University of Singapore cc/SGP cc/JPN dv/10/10/2017 r/4 d/The National University of Singapore is an autonomous research university in Singapore. a/21 Lower Kent Ridge Road, Singapore 1
    Adds customer successfully.

Expected behavior
Should display an error for entering same prefix twice.

**Comment by PremBagda** [comment]
Resolved.
