### ISSUE TITLE
The undo command reverses deletem command.

### ISSUE THREAD

**Issue by chung-ming** [cs2103-ay1819s2-w11-3/main#128]
According to the UG only add, delete, edit and clear commands should work with undo. But the deletem command also works with undo

To Reproduce

    Type the command - deletem 2 3
    Command runs successfully.
    Type the command - undo
    Command runs successfully and shows - undo success - message.

Expected behavior
Undo shouldn't undo this state but a previous state of add, delete, edit or clear commands.
![image](https://user-images.githubusercontent.com/25484540/55614029-a148af80-577b-11e9-8810-ae5d299e62a4.png)

**Comment by nivenang** [comment]
Resolved in PR #135
