### ISSUE TITLE
The command given in the example message of add command doesn't run.

### ISSUE THREAD

**Issue by chung-ming** [cs2103-ay1819s2-w11-3/main#131]
Describe the bug
The add command example message doesn't run when typed by the user.

To Reproduce

    Type the command: add
    Error message is displayed.
    Copy the example command and try to run it.
    Command doesn't run.

Expected behavior
Command should run as it is an example command.
![image](https://user-images.githubusercontent.com/25484540/55614097-c9d0a980-577b-11e9-885f-0aae605f83b4.png)

**Comment by nivenang** [comment]
This bug is due to the example command not having a space between the end of dv parameter and r/ prefix

**Comment by nivenang** [comment]
Resolved in PR #135
