### ISSUE TITLE
The clear command display in the user guide is different from when typed on the application

### ISSUE THREAD

**Issue by chung-ming** [cs2103-ay1819s2-w11-3/main#132]
Describe the bug
When the user types the command - clear - the picture as given in the user guide and what the application shows is different.

To Reproduce

    Type the command - clear
    App shows :
![image](https://user-images.githubusercontent.com/25484540/55614328-3ea3e380-577c-11e9-8cf7-df3ba2f7f9e3.png)
Expected behavior
App should show :
![image](https://user-images.githubusercontent.com/25484540/55614351-495e7880-577c-11e9-903a-e24d994d65ba.png)

**Comment by nivenang** [comment]
Resolved in PR #135
