### ISSUE TITLE
[Chart] Each country bar, a different colour. 

### ISSUE THREAD

**Issue by PremBagda** [cs2103-ay1819s2-w11-3/main#98]
Presently, all the country bars have the same colour. If they have different colours, it will be easier to differentiate. 

![image](https://user-images.githubusercontent.com/35837791/55283955-9cf94c80-539f-11e9-9d0e-5f77bc619f04.png)

**Comment by chung-ming** [comment]
Color variation for Bar Chart, Pie Chart and Line Chart completed. Please reference PR #103.
